[build]
  command = "NODE_OPTIONS='--openssl-legacy-provider' npm run clean && NODE_OPTIONS='--openssl-legacy-provider' npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "16.20.0"
  NPM_VERSION = "8.19.4"
  NODE_OPTIONS = "--openssl-legacy-provider"
  GATSBY_CPU_COUNT = "1"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-lighthouse" 