[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "16.20.0"
  NPM_VERSION = "8.19.4"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-lighthouse" 