[build]
  command = "npm run clean && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  NODE_OPTIONS = ""
  GATSBY_CPU_COUNT = "1"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-lighthouse" 